name: flutter_test_work
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable:
  formz:
  dio:
  http:
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2

  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  web: true
  android_12:
    image: assets/sam_logo.png
    color: '#ffffff'
  color: '#ffffff'
  image: assets/sam_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
